# Generated by Django 5.0.1 on 2025-02-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Comma-separated list of symptoms')),
                ('treatment', models.TextField()),
                ('prevention', models.TextField(blank=True, null=True)),
                ('when_to_see_doctor', models.TextField(blank=True, null=True)),
                ('common_age_groups', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('follow_up_questions', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_predictor.disease')),
            ],
        ),
    ]
