# Generated by Django 5.0.1 on 2025-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='common_age_groups',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='disease',
            name='when_to_see_doctor',
            field=models.TextField(blank=True),
        ),
    ]
