# Generated by Django 5.0.1 on 2025-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_predictor', '0003_sample_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('follow_up_questions', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='disease',
            name='common_age_groups',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(help_text='Comma-separated list of symptoms'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='when_to_see_doctor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
